# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-25 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180925_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainshow',
            old_name='childid1',
            new_name='childcid1',
        ),
        migrations.RenameField(
            model_name='mainshow',
            old_name='childid2',
            new_name='childcid2',
        ),
        migrations.RenameField(
            model_name='mainshow',
            old_name='childid3',
            new_name='childcid3',
        ),
    ]
