# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-25 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180925_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.CharField(max_length=16)),
                ('typename', models.CharField(max_length=50)),
                ('childtypenames', models.CharField(max_length=200)),
                ('typesort', models.IntegerField(default=-1)),
            ],
            options={
                'db_table': 'axf_foodtypes',
            },
        ),
    ]
