"""empty message

Revision ID: ab0eb2c02198
Revises: ef68974f15f3
Create Date: 2018-10-19 14:52:51.222375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab0eb2c02198'
down_revision = 'ef68974f15f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('movieicon', sa.String(length=70), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'movieicon')
    # ### end Alembic commands ###
